export const PERMISSIONS = {
    ADMIN: "Админка",
    USERS: "Пользователи",
    BLOCK_USERS: "Блокировка пользователей",
    NOTIFIES: "Отпрака уведомлений",
    ROLES: "Роли",
    CREATE_ROLES: "Создание ролей",
    UPDATE_ROLES: "Редактирование ролей",
    DELETE_ROLES: "Удаление ролей",
    ISSUE_ROLES: "Выдача ролей",
    THEMES: "Темы",
    CREATE_THEMES: "Создание тем",
    UPDATE_THEMES: "Редактирование тем",
    DELETE_THEMES: "Удаление тем",
    LOGS: "Логирование",
    TESTS: "Тесты",
    CREATE_OFFICIAL_TESTS: 'Создание официальных тестов',
    SUBJECTS: "Предметы",
    CREATE_SUBJECTS: "Создание предметов",
    UPDATE_SUBJECTS: "Редактирование предметов",
    DELETE_SUBJECTS: "Удаление предметов",
    TASKS: "Задания",
    CREATE_TASKS: "Создание заданий",
    UPDATE_TASKS: "Редактирование заданий",
    DELETE_TASKS: "Удаление заданий",
    VERIFY_TASKS: "Верификация заданий",
    COMPLAINTS: "Жалобы",
    ARCHIVE: "Архив",
    CONFIG: "Конфигурация",
};
